import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {geistMono, geistSans} from "@/lib/fonts";
import Appbar from "@/components/Appbar";

export const metadata: Metadata = {
    title: "Nahid Portfolio",
    description: "Generated by Next.js and GSAP",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full overflow-x-hidden px-4 lg:px-0">
            <Appbar/>
            {children}
        </div>
        </body>
        </html>
    );
}
